version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      # PHPアプリからアクセスするデータベースの接続情報
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: my_database
    depends_on:
      - db

  db:
    # MySQLからPostgreSQLの公式イメージに変更
    image: postgres:17-alpine
    environment:
      # PostgreSQLの環境変数はMySQLと異なります
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
